language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - valgrind
      - check
      - python3.4
env:
  global:
  - secure: yiW+hXiZEycKFzF19rLlejJX8BTGbncSisBHyE8uulZee5n7UVGXnG1yvt9+6hz0nvMbxL7r1Daql0xxRHXUFB9VYVUKhF0ycHyJO5ze87U51mlIKAL8UnCkmxpkHNdxY45olEdK+mEbZBtot67nenlwGDfxLI7laITkR8IBAvY=
  - secure: WVOHmRlzHZhuYqpTVFR2ZjdVDugr/EGEZGhnkWFFh6DE2zfa+na8WSLQdynHjTH1sL2DMg+p4l8siLoKk6Kn9wh+Wah2GP54oKQNIvt+Zl0olTR8TZq/uEo1iU4dqsDbMscId2xK7imdQ9wMKXV0t/bqhjiFR/wxheR96WxvIVs=
  - M3_HOME=/usr/local/maven

before_install:
  - curl -L https://static.rust-lang.org/rustup.sh | sh -s -- --channel=stable --yes --prefix=$PWD --disable-sudo
  - export PATH=$PATH:$PWD/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
  - mkdir $HOME/bin && ln -s $(which python3.4) $HOME/bin/python3 && export PATH="$HOME/bin:$PATH"
  - mvn install -Dmaven.test.skip=true
script:
  - mvn clean test
  - mvn checkstyle:check
  - . ./clitest.sh
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - ./deploy.sh
os:
  - linux
  - osx
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
matrix:
  allow_failures:
  - os: osx
notifications:
  slack:
    secure: elwVbriXdc/RkeP3UfVpSC0N6mbdk60ro7Pu1+2ddktmgQIEHjAVSdzpy2FLGTz/gK2MEXo2XU1rSg3t8GqlJNh1RTASzhyhcCUJTa7UdKe84mcRWDxJffunQKsBpUJv71tXBy1OyL8pcdnw1qkpr5NDyqXvBk67VwepVqy8em4=
